name: test
on: push

jobs:
  run-job:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{steps.step_branch_name.branch_name}}
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Run
        run: echo "Hello world"
      - name: Java version
        continue-on-error: true
        run: java --version
      - name: NPM version
        continue-on-error: true
        run: npm --version
      - name: Create file and show dir
        run: echo test > test.txt && ls -R
        continue-on-error: true
      - name: Python
        run: python --version
        continue-on-error: true
      - name: Python3
        run: python3 --version
        continue-on-error: true
      - name: Run command
        id: step_branch_name
        run: |
          output=$(python3 branch_name.py ${{ github.ref }})
          echo "::set-output name=branch_name::$output"
  python-job:
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        run: echo ${{needs.run.job.outputs.branch_name}}
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
  
