name: test
on: push

jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: echo "Hello world"
      - name: Java version
        continue-on-error: true
        run: java --version
      - name: NPM version
        continue-on-error: true
        run: npm --version
